
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

array = np.arange(10)

print("Array:")
print(array)

Array:
[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

### It is not possible to reshape an array of size 10 into a shape of (3,3)
    To reshape the above array we require total 9 elements

In [ ]:


array_2d = array_1d.reshape(3, 3)

print("\nReshaped 3x3 Matrix:")
print(array_2d)

In [3]:
import numpy as np

array = np.arange(1,10)

print("Array:")
print(array)

reshaped_array = array.reshape(3, 3)
reshaped_array

Array:
[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [5]:
array_element = reshaped_array[1,1]
array_element

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [18]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [19]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

array1 = np.sum(array)
array2 = np.mean(array)
array3 = np.std(array)

print("Sum:", array1)
print("Mean:", array2)
print("Standard Deviation:", array3)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [20]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

array1 = array.reshape(2, 3)

print(array1)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [21]:
import numpy as np

array = np.random.randint(0, 100, size=(5, 5))

print(array)

[[57 95 27 72 50]
 [15 54  6 42 39]
 [76 44 61 41 19]
 [66 61 21 92 58]
 [62 53 91 24 87]]


Replace all values in the sub-array with a specific value.


In [22]:
import numpy as np

random_array = np.random.randint(0, 100, size=(5, 5))

print("Original Array:")
print(random_array)

sub_array_value = 999
random_array[1:4, 1:4] = sub_array_value

print("\nModified Array:")
print(random_array)

Original Array:
[[60 30 18 23 51]
 [14 36 25 31 60]
 [99 67 30 91  5]
 [75 38 36 19  0]
 [10 64 86 89 88]]

Modified Array:
[[ 60  30  18  23  51]
 [ 14 999 999 999  60]
 [ 99 999 999 999   5]
 [ 75 999 999 999   0]
 [ 10  64  86  89  88]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [23]:
import numpy as np

original_array = np.array([[1, 2], 
                           [3, 4], 
                           [5, 6], 
                           [7, 8]])

sub_array = original_array[[1, 3], :]

print("Original Array:")
print(original_array)

print("\nExtracted Sub-Array:")
print(sub_array)

Original Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Extracted Sub-Array:
[[3 4]
 [7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [8]:
import numpy as np

array = np.array([0, 1, 2])
array

array1 = np.tile(array, (3,1))
array1

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [11]:
array_1d = np.array([1, 2, 3])

Final_array = array1 + array_1d

print(Final_array)

[2 4 6]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [20]:
import numpy as np

array1 = np.random.randint(1, 10, (3, 3)) 
array2 = np.random.randint(1, 10, (3, 3))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

Array 1:
[[1 4 9]
 [6 5 7]
 [1 5 9]]

Array 2:
[[8 2 4]
 [6 7 8]
 [2 7 4]]


In [21]:
horizontal = np.concatenate((array1, array2), axis=1) 
vertical = np.concatenate((array1, array2), axis=0)

print("\nConcatenated Horizontally:") 
print(horizontal)

print("\nConcatenated Vertically:") 
print(vertical)


Concatenated Horizontally:
[[1 4 9 8 2 4]
 [6 5 7 6 7 8]
 [1 5 9 2 7 4]]

Concatenated Vertically:
[[1 4 9]
 [6 5 7]
 [1 5 9]
 [8 2 4]
 [6 7 8]
 [2 7 4]]


In [22]:
split_horizontal = np.hsplit(horizontal, 2) 
split_vertical = np.vsplit(vertical, 2)

print("\nSplit Horizontal Arrays:") 
print(split_horizontal)

print("\nSplit Vertical Arrays:") 
print(split_vertical)


Split Horizontal Arrays:
[array([[1, 4, 9],
       [6, 5, 7],
       [1, 5, 9]]), array([[8, 2, 4],
       [6, 7, 8],
       [2, 7, 4]])]

Split Vertical Arrays:
[array([[1, 4, 9],
       [6, 5, 7],
       [1, 5, 9]]), array([[8, 2, 4],
       [6, 7, 8],
       [2, 7, 4]])]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [23]:
def find_mode(arr):
    count_dict = {}
    
    for num in arr:
        if num in count_dict:
            count_dict[num] += 1
        else:
            count_dict[num] = 1
    
    max_count = max(count_dict.values())
    
    modes = [num for num, count in count_dict.items() if count == max_count]
    
    return modes

arr = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]
print(find_mode(arr))

[1]


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

